version: '3.9'

services:
  springboot-demo:
    image: kkk2099/kkk:springboot-demo-1.0
    environment:
      - JVM_MEM=1G
    volumes:
      - ./logs:/data/apps/logs
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10001/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
 