apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demo-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-demo
      version: v1.0.0
  template:
    metadata:
      labels:
        app: springboot-demo
        version: v1.0.0
    spec:
      containers:
        - name: springboot-demo
          image: kkk2099/kkk:springboot-demo-1.0
          env:
            - name: JVM_MEM
              value: "1G"
            - name: APP_VERSION
              value: "1.0.0"
          ports:
            - containerPort: 10001
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 10001
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 10001
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demo-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-demo
      version: v2.0.0
  template:
    metadata:
      labels:
        app: springboot-demo
        version: v2.0.0
    spec:
      containers:
        - name: springboot-demo
          image: kkk2099/kkk:springboot-demo-1.0
          env:
            - name: JVM_MEM
              value: "1G"
            - name: APP_VERSION
              value: "2.0.0"
          ports:
            - containerPort: 10001
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 10001
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 10001
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-demo
spec:
  selector:
    app: springboot-demo
  ports:
    - protocol: TCP
      port: 10001  # 你希望暴露的端口
      targetPort: 10001  # 容器内部端口
  type: ClusterIP


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-demo-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  # 添加这一行
  rules:
    - host: app1.konglingan.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: springboot-demo
                port:
                  number: 10001






